### ISSUE TITLE
【Learn】インストール関連のページ構成をITAと同様にしたい

### ISSUE THREAD

**Issue by wakkysan** [exastro-suite/oase-docs#30]
ITAのコミュニティページでは「Online」「 Offline」 「Version up」「Container」 とタブが分かれているのと同様に、OASEのコミュニティページも同様にしてほしい。

**Comment by Yuko-K** [comment]
[Operation Autonomy Support Engine オフラインインストール.pdf](https://github.com/exastro-suite/oase-docs/files/6120673/Operation.Autonomy.Support.Engine.pdf)
[Operation Autonomy Support Engine オンラインインストール.pdf](https://github.com/exastro-suite/oase-docs/files/6120675/Operation.Autonomy.Support.Engine.pdf)
[Operation Autonomy Support Engine バージョンアップインストール.pdf](https://github.com/exastro-suite/oase-docs/files/6120676/Operation.Autonomy.Support.Engine.pdf)


※dockerインストール情報（OASEはdocker版のみ）
--------------------------------------------------
お手持ちのコンテナ環境にOperation Autonomy Support Engineをすぐに起動できます。
インターネットに接続できる必要があります。
コンテナ起動後、下記の Operation Autonomy Support Engineクイックスタートを始めれば、
すぐに Operation Autonomy Support Engineの魅力的なインターフェースを体験いただくことが可能です。

Step - 1 :コンテナの起動

Docker
`#` docker run --privileged --add-host=exastro-oase:127.0.0.1 -d -p 8080:80 -p 10443:443 --name exastro01 exastro/oase:x.x.x

※ポート番号(8080,10443)とバージョン(x.x.x)は適宜変更してください。


Step - 2 :Operation Autonomy Support Engineコンソールにアクセス

https://[Container-Host-IP]:10443/oase_web/top/login or http://[Container-Host-IP]:8080/oase_web/top/login

※ポート番号(8080,10443)は適宜変更してください。


Step - 3 :ログイン
ログイン画面が表示されたら、指定のログインID、初期パスワードを入力して、[ログイン]ボタンをクリックしてください。

・ログインID ： administrator
・初期パスワード ： oaseoaseoase

※インストール後に初めてログインした場合は、「パスワード変更画面」に遷移します。
※パスワード変更画面から、初期パスワードを変更してください。

--------------------------------------------------

**Comment by katokeita** [comment]
更新しました。
https://exastro-suite.github.io/oase-docs/learn_ja.html
https://exastro-suite.github.io/oase-docs/downloads_ja.html
