### ISSUE TITLE
Exastro OASEのクイックスタートを差し替えたい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/oase-docs#37]
OASEのクイックスタートの資料の差し替えをお願いします。
[OASE-quickstart_ja.pdf](https://github.com/exastro-suite/oase-docs/files/6120594/OASE-quickstart_ja.pdf)

**Comment by katokeita** [comment]
差し替えました。
https://exastro-suite.github.io/oase-docs/learn_ja.html
