### ISSUE TITLE
【FAQ】【Translate】2021年4月分_01

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/oase-docs#41]
OASEのFAQの翻訳・掲載をお願いします。

■対象ファイル
【Exastro OASE】FAQ管理シート.xlsx
■対象No
No.1～No.5

※掲載は、日本語版はNo.1～No.5、英語版はNo.1、No.2をお願いします。(No.3～No.5はマニュアル翻訳後に掲載します)

**Comment by JoachimLarsen** [comment]
翻訳完成しました。どうぞご確認ください。
no.3-5の参照URLは日本語版のURLのまま記入してますのでご注意ください。

**Comment by katokeita** [comment]
OASE FAQ公開しました。
https://exastro-suite.github.io/oase-docs/faq.html
https://exastro-suite.github.io/oase-docs/faq_ja.html
