### ISSUE TITLE
システム連携の画像を更新してほしい

### ISSUE THREAD

**Issue by wreathvine** [exastro-suite/oase-docs#46]
## 概要
v1.3.0 リリースに伴い外部のシステムと連携できる機能が追加された。
コンテンツ上の情報が古いため画像の更新をしてほしい。

![image](https://user-images.githubusercontent.com/83527822/118749747-1cf11200-b899-11eb-9052-cc3bd0e89710.png)

#### 監視ソフトウェア
・Zabbix
・Prometheus → v1.3 でリリースしたため"Comming SOON"外す
・CloudWatch
#### 作業自動化ソフトウェア
・Exastro
・Airflow → メール
・Jenkins → Teams
### 対象となる画像
・https://exastro-suite.github.io/oase-docs/asset/img/oase_overview_ja.png
・https://exastro-suite.github.io/oase-docs/asset/img/oase_chain_image.png
その他あれば適宜。

**Comment by katokeita** [comment]
システム連携の画像を更新しました。
https://exastro-suite.github.io/oase-docs/overview_ja.html
https://exastro-suite.github.io/oase-docs/overview.html
