### ISSUE TITLE
「検証の場合は、アクションの直前まで実行」という表現を修正してほしい

### ISSUE THREAD

**Issue by wreathvine** [exastro-suite/oase-docs#47]
## 概要
「検証の場合は、アクションの直前まで実行」という表現が分かりづらいので、修正してほしい

![image](https://user-images.githubusercontent.com/83527822/118749833-414cee80-b899-11eb-8356-0a16aec4542e.png)

### 現行
「検証の場合は、アクションの直前まで実行」
### 修正案
「検証の場合は実行しない」
### 対象の画像
・https://exastro-suite.github.io/oase-docs/asset/img/staging_confirmation.png

**Comment by katokeita** [comment]
下記文言の翻訳をお願いできますでしょうか。
「検証の場合は実行しない」

**Comment by JoachimLarsen** [comment]
If it is verification, it doesn't get executed.

でお願いします。

**Comment by katokeita** [comment]
画像修正しました。
https://exastro-suite.github.io/oase-docs/overview_ja.html
https://exastro-suite.github.io/oase-docs/overview.html

**Comment by wreathvine** [comment]
ありがとうございました。
