### ISSUE TITLE
Learnページに、各Learn資料がどこを表しているかわかるような絵を載せてほしい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/oase-docs#48]
OASEのLearnページに、各Learnの資料が、どの範囲をカバーしているかわかるような絵を載せてほしいです。
可能であれば、Learn資料名を選択すると、該当記載部分に飛ぶようにしてもらえると助かります。
(「クイックスタート」を押すと、クイックスタートの掲載部分にジャンプ)

絵の場所は、
"Exastro Operation Autonomy Support Engine を触ってみよう"の文言の下を想定しています！

【イメージ図】
![image](https://user-images.githubusercontent.com/62239529/118767902-4ae64e80-b8b9-11eb-95ce-6b27c3bde772.png)

**Comment by JoachimLarsen** [comment]
英語版はこちらを使いください
[Learn資料概要_EN.xlsx](https://github.com/exastro-suite/oase-docs/files/6506705/Learn._EN.xlsx)

**Comment by katokeita** [comment]
Learn MAP 追加しました。
https://exastro-suite.github.io/oase-docs/learn_ja.html
https://exastro-suite.github.io/oase-docs/learn.html
