### ISSUE TITLE
OASEの概要イメージ図の連携ソフトウェア部分ラインナップ変更をしてほしい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/oase-docs#52]
OASEの概要イメージ図ですが、自動化ソフトウェアの部分を、
大きく「連携ソフトウェア」として、その中にサブカテゴリとして、「自動作業」と「通知」に分けた図にしたいです。

ラインナップは下記でお願いします。
自動作業：ITA
通知：ServiceNow、メール

![image](https://user-images.githubusercontent.com/62239529/119604304-ca2fd100-be29-11eb-9121-417a00b072d0.png)

**Comment by Yuko-K** [comment]
翻訳は、
「連携ソフトウェア」
「自動作業」
「通知」
の３ワードの対応をお願いします。

**Comment by JoachimLarsen** [comment]
連携ソフトウェア：Linking software
自動作業：Automatic operations
通知：Notification

でお願いします

**Comment by Yuko-K** [comment]
@katokeita 
こちらも修正でお願いします
![image](https://user-images.githubusercontent.com/62239529/119605164-44148a00-be2b-11eb-984d-7a41ad3a982e.png)

**Comment by katokeita** [comment]
自動化ソフトウェア部分を修正しました。
https://exastro-suite.github.io/oase-docs/overview_ja.html
https://exastro-suite.github.io/oase-docs/overview.html

合わせて、
Learn MAPの自動化ソフトウェアを＞連携ソフトウェアに修正しました。
