### ISSUE TITLE
Exastro OASEのウェビナーページが欲しい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/oase-docs#53]
ITAと同様のウェビナーページが欲しいです。
ラインナップは下記です。

![image](https://user-images.githubusercontent.com/62239529/119633322-96b26e00-be4c-11eb-8a05-bd55eb660544.png)

**Comment by Yuko-K** [comment]
追加で、ウェビナーのアップもお願いいたします。

OASE Version：Ver1.3.0
アーカイブ：https://youtu.be/vtOXJgAXyy0
セミナーコード：Ex-C05-01
概要：Exastro OASEの概要と、オールインワン構成でのインストール、および活用方法をデモを交えて解説しております。Exastro OASEを初めてお使いになる方にピッタリのビギナーコースです。

**Comment by katokeita** [comment]
Webinarページ作成しました。
https://exastro-suite.github.io/oase-docs/webinar_ja.html
