### ISSUE TITLE
Learn オフラインインストールのアップロード依頼

### ISSUE THREAD

**Issue by m-kawata-git** [exastro-suite/oase-docs#55]
Learn資料になります、オフラインインストールのアップロードをお願いします。
[Operation Autonomy Support Engine オフラインインストール.pdf](https://github.com/exastro-suite/oase-docs/files/6557326/Operation.Autonomy.Support.Engine.pdf)

**Comment by katokeita** [comment]
オフラインインストール差し替えました。
https://exastro-suite.github.io/oase-docs/learn_ja.html
