### ISSUE TITLE
Learn バージョンアップインストールのアップロード依頼

### ISSUE THREAD

**Issue by yuya0arai** [exastro-suite/oase-docs#56]
Learn資料になります、バージョンアップインストールのアップロードをお願いします。
[Operation Autonomy Support Engine バージョンアップインストール.pdf](https://github.com/exastro-suite/oase-docs/files/6557331/Operation.Autonomy.Support.Engine.pdf)

**Comment by katokeita** [comment]
バージョンアップインストール差し替えました。
https://exastro-suite.github.io/oase-docs/learn_ja.html
