### ISSUE TITLE
OASEの構成図を載せたい

### ISSUE THREAD

**Issue by Yuko-K** [exastro-suite/oase-docs#61]
コミュニティサイトのOASE Learnページに、ITAの「Exastro IT Automation のデプロイ例」と同じように
OASEの構成図を載せたいです。

今回掲載する構成
・オールインワン構成
・ハイアベイラビリティ　－サーバ分散型HA構成－
※ハイアベイラビリティのオールインワン型は、動作確認後、改めて掲載を依頼。

![image](https://user-images.githubusercontent.com/62239529/122517510-14802880-d04b-11eb-9a0f-0351caa962e1.png)
![image](https://user-images.githubusercontent.com/62239529/122517549-2235ae00-d04b-11eb-9476-473373594225.png)

**Comment by JoachimLarsen** [comment]
[OASE構成図翻訳.xlsx](https://github.com/exastro-suite/oase-docs/files/6675258/OASE.xlsx)
英語版はこちらを使いください。

**Comment by nec-takeo-ekiba** [comment]
ありがとうございました。
